name: Storybook
on:
  push:
    branches:
      - main # if any push happens on branch `main`, run this workflow. You could also add `paths` to detect changes in specific folder

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - uses: actions/setup-node@v3
        with:
          node-version: 20
      
      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install and Build
        run: |
          pnpm install
          pnpm storybook:publish

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          branch: gh-pages
          folder: storybook-static
